canonical: http://shinny.org
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: fhir.shinny
name: SHINNYIG
status: draft
version: 0.1.0
dependencies:
  hl7.fhir.us.core:
    version: 6.0.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: hl7_fhir_us_core
